### ISSUE TITLE
Server Password

### ISSUE THREAD

**Issue by invisiblepinkcrystals** [oddluck/idlerpg-themable#2]
Hi! Awesome project. 👍 

Maybe more a feature request than an actual issue:
The bot cannot connect to IRC servers protected by a password.

As a total newbie, I have no idea how complex it would be for you to add such an option—but if you could, rest assured that it would be greatly appreciated.

Thanks for your attention. :)

**Comment by oddluck** [comment]
This qualifies as an issue certainly. I will look into supporting password protected servers. Thank you for the issue. Appreciate any and all feedback.

**Comment by oddluck** [comment]
Password protected server support has been added to bot.pl and irpg.conf. Uncomment the server_pass line in irpg.conf and supply your password. I don't know any password protected servers to test on but I believe this will work. Please let me know if it works for you and I will close the issue.

**Comment by oddluck** [comment]
Marking issue closed unless I hear otherwise.
